accent: "#4aa5f0"
background: "#16161e"
details: darker
foreground: "#d9d9d9"
terminal_colors:
  bright:
    black: "#444b6a"
    blue: "#7da6ff"
    cyan: "#0db9d7"
    green: "#b9f27c"
    magenta: "#bb9af7"
    red: "#ff7a93"
    white: "#d9d9d9"
    yellow: "#ff9e64"
  normal:
    black: "#1a1b26"
    blue: "#7aa2f7"
    cyan: "#2ac3de"
    green: "#9ece6a"
    magenta: "#ad8ee6"
    red: "#f7768e"
    white: "#a9b1d6"
    yellow: "#e0af68"
